<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>GlobalLogic Self Appraisal form</title>
    <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
	<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css'>
	<link rel='stylesheet prefetch' href='http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css'>
	<link rel="stylesheet" href="/css/appraisal_style.css">
    <link rel="stylesheet" href="/css/rangeSlider.css">
  <style>
  legend {
   border-bottom: 1px solid #ccc !important;
   }
   .form-group {
   text-align:left !important;
   }
   
   output {
            display: block;
            font-size: 30px;
            font-weight: bold;
            text-align: center;
            /* margin: 30px 0; */
            width: 100%;
			margin:-39px 0 0 193px;
        }
		
		*,
        *:before,
        *:after {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
  </style>  
    
    
  </head>

  <body>

    <div class="container">

<form class="well form-horizontal" action="<?php echo '/'.$action; ?>" method="post"  id="contact_form">
<fieldset>
<?php
                        echo $this->flashMessenger()
                                ->setMessageOpenFormat('<div%s><p>')
                                ->setMessageSeparatorString('</p><p>')
                                ->setMessageCloseString('</p></div>')
                                ->render('success', array('alert', 'alert-success'));
                       ?>
<!-- Form Name -->
<legend>GlobalLogic Self Appraisal form for the period 2015-16</legend>
<p>We recommend that the Self-Appraisal be completed and submitted to your manager as per timelines.</p>				
<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Name</label>  
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="name" placeholder="Name" class="form-control"  type="text" value="<?php echo isset($emp_details->name)?$emp_details->name:''; ?>" <?php echo isset($emp_details->name)?'disabled':''; ?>/>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Email</label>  
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input  name="email" placeholder="Your Email ID" class="form-control"  type="email" value="<?php echo isset($emp_details->email)?$emp_details->email:''; ?>" <?php echo isset($emp_details->email)?'disabled':''; ?>/>
    </div>
  </div>
</div>
<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >GlobalLogic EID</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="globallogic_eid" placeholder="GlobalLogic EID" class="form-control"  type="text" value="<?php echo isset($emp_details->eid)?$emp_details->eid:''; ?>" <?php echo isset($emp_details->eid)?'disabled':''; ?>/>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Designation</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="designation" placeholder="Designation" class="form-control"  type="text" value="<?php echo isset($emp_details->designation)?$emp_details->designation:''; ?>" <?php echo isset($emp_details->designation)?'disabled':''; ?>/>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Process</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="process" placeholder="Process" class="form-control"  type="text" value="<?php echo isset($emp_details->process)?$emp_details->process:''; ?>" <?php echo isset($emp_details->process)?'disabled':''; ?>/>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >DOJ</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="doj" placeholder="DOJ" class="form-control"  type="text" value="<?php echo isset($emp_details->doj)?date('d-m-Y', strtotime($emp_details->doj)):''; ?>" <?php echo isset($emp_details->doj)?'disabled':''; ?>/>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >SuperVisor / Manager email</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="supervisor_or_manager_email" placeholder="SuperVisor / Manager Email" class="form-control"  type="email" value="<?php echo isset($mngr_email)?$mngr_email:''; ?>" <?php echo isset($mngr_email)?'disabled':''; ?>/>
    </div>
  </div>
</div>
<hr>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Major Responsibilities / KRA's</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="major_responsibilities" placeholder="Major Responsibilities / KRA's" class="form-control"  cols='20' rows='5' <?php echo isset($feedBack->major_resoponsbilties)?'disabled':''; ?>><?php echo isset($feedBack->major_resoponsbilties)?$feedBack->major_resoponsbilties:''; ?></textarea>
    </div>
  </div>
</div>


<!-- Text input

<div class="form-group">
  <label class="col-md-4 control-label" >Manager Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="manager_comments" placeholder="Manager Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>
-->
<hr>
<input type="hidden" name="period" value="2015-16" />
<!-- dns changes start-->
<?php
foreach($appraisals as $ky => $val){
?>
<!-- Text input-->

<div class="form-group">
    <legend><?php echo is_array($val)?$val['type']:$val->type;?></legend>
  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <div>
        <input name="self_rating_label_<?php echo is_array($val)?$val['id']:$val->id; ?>" type="hidden" value="<?php echo is_array($val)?$val['id']:$val->id; ?>">
        <input name="self_rating_<?php echo is_array($val)?$val['id']:$val->id; ?>" type="range" min="0" max="5" data-rangeSlider value="<?php echo is_array($val)?$val['aprsl_rate_id']:'';?>" <?php echo is_array($val)?'disabled':'';?>/>
	<output name="self_rate_result_<?php echo is_array($val)?$val['id']:$val->id; ?>"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers_<?php echo is_array($val)?$val['id']:$val->id; ?>" placeholder="Key Pointers" class="form-control"  cols='20' rows='5' <?php echo is_array($val)?'disabled':'';?>><?php echo is_array($val)?$val['key_pointers']:'';?></textarea>
    </div>
  </div>
</div>

    <?php
    if($role == 1){
    ?>
    <!-- Text input-->

    <div class="form-group">
       <legend>Manager Review</legend>
      <label class="col-md-4 control-label" >Manager's Rating</label> 
        <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
            <div>
        <input name="managers_rating_<?php echo is_array($val)?$val['id']:$val->id; ?>" type="range" min="0" max="5" data-rangeSlider value="<?php echo is_array($val)?$val['manager_ratting']:'';?>" />
            <output name="managers_rate_result_<?php echo is_array($val)?$val['id']:$val->id; ?>"></output>
        </div>
      </div>
    </div>

    <!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label" >Comments</label> 
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
      <textarea name="comments_<?php echo is_array($val)?$val['id']:$val->id; ?>" placeholder="Comments" class="form-control"  cols='20' rows='5'><?php echo is_array($val)?$val['comment']:'';?> </textarea>
        </div>
      </div>
    </div>
    <?php } ?>
<hr>
<?php
}//end of foreach
?>
<!-- dns changes end-->

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Extra-mile(optional):Accepted targeted result beyond common call of duty and acts toward achieving given result</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="extra_mile" placeholder="Extra-mile(optional)" class="form-control"  cols='20' rows='5' <?php echo isset($feedBack->extra_mile)?'disabled':''; ?>><?php echo isset($feedBack->extra_mile)?$feedBack->extra_mile:''; ?></textarea>
    </div>
  </div>
</div>

<?php
if($role == 1){
?>
<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Manager/Lead Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="extra_mile_comments" placeholder="Manager/Lead Comments" class="form-control"  cols='20' rows='5'><?php echo isset($feedBack->e_manager_comment)?$feedBack->e_manager_comment:''; ?></textarea>
    </div>
  </div>
</div>
<?php } ?>
<hr>
<div class="form-group">
  <label class="col-md-4 control-label" >Notable Accomplishments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="notable_accom_comments" placeholder="Notable Accomplishments" class="form-control"  cols='20' rows='5' <?php echo isset($feedBack->notable_accomplishments)?'disabled':''; ?>><?php echo isset($feedBack->notable_accomplishments)?$feedBack->notable_accomplishments:''; ?></textarea>
    </div>
  </div>
</div>
<?php
if($role == 1){
?>
<div class="form-group">
  <label class="col-md-4 control-label" >Manager/Lead Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="notable_accom_comments" placeholder="Manager/Lead Comments" class="form-control"  cols='20' rows='5'><?php echo isset($feedBack->n_manager_comment)?$feedBack->n_manager_comment:''; ?></textarea>
    </div>
  </div>
</div>

<hr>
<hr>
<div class="form-group">
  <label class="col-md-4 control-label" style="font-size:bold;font-size:19px">Overall Manager's Feedback with inline Self Rating</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="overall_feedback" placeholder="Feedback" class="form-control"  cols='20' rows='5'><?php echo isset($feedBack->overall_fb)?$feedBack->overall_fb:''; ?></textarea>
    </div>
  </div>
</div>
<?php } ?>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
    <button type="submit" class="btn btn-warning" >Submit <span class="glyphicon glyphicon-send"></span></button>
    <button type="button" class="btn btn-warning" ><a href="/dashboard">Back </a><span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>
<script src="/js/index.js"></script>
<script src="/js/rangeSlider.js"></script>
<script>
    (function () {

        var selector = '[data-rangeSlider]',
            elements = document.querySelectorAll(selector);

        // Example functionality to demonstrate a value feedback
        function valueOutput(element) {
            var value = element.value,
                output = element.parentNode.getElementsByTagName('output')[0];
            output.innerHTML = value;
        }

        for (var i = elements.length - 1; i >= 0; i--) {
            valueOutput(elements[i]);
        }

        Array.prototype.slice.call(document.querySelectorAll('input[type="range"]')).forEach(function (el) {
            el.addEventListener('input', function (e) {
                valueOutput(e.target);
            }, false);
        });
		
        // Basic rangeSlider initialization
        rangeSlider.create(elements, {

            // Callback function
            onInit: function () {
            },

            // Callback function
            onSlideStart: function (value, percent,  position) {
                console.info('onSlideStart', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            },

            // Callback function
            onSlide: function (value, percent,  position) {
                console.log('onSlide', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            },

            // Callback function
            onSlideEnd: function (value, percent,  position) {
                console.warn('onSlideEnd', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            }
        });

    })();
</script>

    
    
    
  </body>
</html>

