<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>GlobalLogic Self Appraisal form</title>
    <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
	<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css'>
	<link rel='stylesheet prefetch' href='http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css'>
	<link rel="stylesheet" href="css/appraisal_style.css">
    <link rel="stylesheet" href="css/rangeSlider.css">
  <style>
  legend {
   border-bottom: 1px solid #ccc !important;
   }
   .form-group {
   text-align:left !important;
   }
   
   output {
            display: block;
            font-size: 30px;
            font-weight: bold;
            text-align: center;
            /* margin: 30px 0; */
            width: 100%;
			margin:-39px 0 0 193px;
        }
		
		*,
        *:before,
        *:after {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
  </style>  
    
    
  </head>

  <body>

    <div class="container">

<form class="well form-horizontal" action="/appraisal" method="post"  id="contact_form">
<fieldset>

<!-- Form Name -->
<legend>GlobalLogic Self Appraisal form for the period 2015-16</legend>
<p>We recommend that the Self-Appraisal be completed and submitted to your manager as per timelines.</p>				
<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Name</label>  
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="name" placeholder="Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >GlobalLogic EID</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="globallogic_eid" placeholder="GlobalLogic EID" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Designation</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="designation" placeholder="Designation" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Process</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="process" placeholder="Process" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >DOJ</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="doj" placeholder="DOJ" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >SuperVisor / Manager email</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-send"></i></span>
  <input name="supervisor_or_manager_name" placeholder="SuperVisor / Manager Email" class="form-control"  type="email">
    </div>
  </div>
</div>
<hr>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Major Responsibilities / KRA's</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="major_responsibilities" placeholder="Major Responsibilities / KRA's" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Manager Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="manager_comments" placeholder="Manager Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
 <legend>Taking Responsibility:(completes assignments in a thorough,accurate and timely manner that achieves expected outcomes)</legend>
  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
	<div>
    <input name="self_rating" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
   <legend>Manager Review</legend>
  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating" placeholder="Manager's Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="managers_rating" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
   <legend>Problem Solving:(Identifies and analyzes problems; formulates alternative solutions; takes or recommends appropriate actions; follows upto ensure problems are resolved)</legend>
  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <div>
    <input name="self_rating1" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result1" ></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers1" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>


<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>
  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating1" placeholder="Manager's Rating" class="form-control"  type="text">
   </div>-->
    <div>
    <input name="managers_rating1" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result1" ></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments1" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Collaboration/Teamwork:(Maintain harmonious and effective work relationships with co-workers and team members)</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating2" placeholder="Self Rating" class="form-control"  type="text">
   </div>-->
   <div>
    <input name="self_rating2" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result2"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers2" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating2" placeholder="Manager's Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="managers_rating2" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result2"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments2" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Produces functional deliverables with respect to committed quality level</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating3" placeholder="Self Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="self_rating3" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result3"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers3" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating3" placeholder="Manager's Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="managers_rating3" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result3"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments3" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Coverage planning with respect to business requirement(Only for those handling teams)</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating4" placeholder="Self Rating" class="form-control"  type="text">
   </div>-->
   <div>
    <input name="self_rating4" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result4"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers4" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating4" placeholder="Manager's Rating" class="form-control"  type="text">
   </div>-->
   <div>
    <input name="managers_rating4" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result4"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments4" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>


<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Providing scope to Professional development of team members</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating5" placeholder="Self Rating" class="form-control"  type="text">
   </div>-->
   <div>
    <input name="self_rating5" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result5"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers5" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating5" placeholder="Manager's Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="managers_rating5" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result5"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments5" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Client relationship management(Escalation management, response to client,sharing reports on timely basis,showcasing organisation commitment)</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating6" placeholder="Self Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="self_rating6" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result6"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers6" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating6" placeholder="Manager's Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="managers_rating6" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result6"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments6" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<!-- Text input-->

<div class="form-group">
	<legend>Self Learning (Openness for learning new skills and capabilities,participation in skill development programs driven by organisation,Apply learnings on the job)</legend>

  <label class="col-md-4 control-label" >Self Rating(Rate yourself)</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
    <!--<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="self_rating7" placeholder="Self Rating" class="form-control"  type="text">
    </div>-->
	<div>
    <input name="self_rating7" type="range" min="0" max="5" data-rangeSlider>
	<output name="self_rate_result7" ></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Key Pointers</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="key_pointers7" placeholder="Key Pointers" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>

<!-- Text input-->

<div class="form-group">
	<legend>Manager Review</legend>

  <label class="col-md-4 control-label" >Manager's Rating</label> 
    <div class="col-md-4 inputGroupContainer" style="margin-top:7px;">
   <!-- <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
  <input name="managers_rating7" placeholder="Manager's Rating" class="form-control"  type="text">
   </div>-->
   <div>
    <input name="managers_rating7" type="range" min="0" max="5" data-rangeSlider>
	<output name="managers_rate_result7"></output>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="comments7" placeholder="Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<hr>
<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Extra-mile(optional):Accepted targetted result beyond commom call of duty and acts toward achieving given result</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="extra_mile" placeholder="Extra-mile(optional)" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Manager/Lead Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="manager_or_lead_comments" placeholder="Manager/Lead Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<div class="form-group">
  <label class="col-md-4 control-label" >Notable Accomplishments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="notable_accomplishments" placeholder="Notable Accomplishments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" >Manager/Lead Comments</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="manager_or_lead_comments1" placeholder="Manager/Lead Comments" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<hr>
<hr>
<hr>
<hr>
<div class="form-group">
  <label class="col-md-4 control-label" style="font-size:bold;font-size:19px">Overall Manager's Feedback with inline Self Rating</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  <textarea name="overall_feedback" placeholder="Feedback" class="form-control"  cols='20' rows='5'></textarea>
    </div>
  </div>
</div>

<!-- Success message -->
<div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
    <button type="submit" class="btn btn-warning" >Submit <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>
<script src="js/index.js"></script>
<script src="js/rangeSlider.js"></script>
<script>
    (function () {

        var selector = '[data-rangeSlider]',
            elements = document.querySelectorAll(selector);

        // Example functionality to demonstrate a value feedback
        function valueOutput(element) {
            var value = element.value,
                output = element.parentNode.getElementsByTagName('output')[0];
            output.innerHTML = value;
        }

        for (var i = elements.length - 1; i >= 0; i--) {
            valueOutput(elements[i]);
        }

        Array.prototype.slice.call(document.querySelectorAll('input[type="range"]')).forEach(function (el) {
            el.addEventListener('input', function (e) {
                valueOutput(e.target);
            }, false);
        });
		
        // Basic rangeSlider initialization
        rangeSlider.create(elements, {

            // Callback function
            onInit: function () {
            },

            // Callback function
            onSlideStart: function (value, percent,  position) {
                console.info('onSlideStart', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            },

            // Callback function
            onSlide: function (value, percent,  position) {
                console.log('onSlide', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            },

            // Callback function
            onSlideEnd: function (value, percent,  position) {
                console.warn('onSlideEnd', 'value: ' + value, 'percent: ' + percent, 'position: ' + position);
            }
        });

    })();
</script>

    
    
    
  </body>
</html>

