<?php $role_id = 0;//(int) $this->layout()->users_info->user_role; ?>
<div class="header-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-lg-4 text-left pull-left"><a href="/dashboard" class="logo">GlobalLogic Appraisal System</a></div>
            <div class="col-md-8 col-sm-8 col-lg-8 text-right pull-right top-link">

                <div class="menu-hover">
                    <a href="#" ><i class="fa fa-user"></i>
                        <?php //echo $this->layout()->users_info->name; ?></a>
                    <div class="sub" style="display: block;">
                        <a style="font-size:14px;" href="/logout"><i class="fa fa-power-off"></i> Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
