<?php $role_id = 0;//(int) $this->layout()->users_info->user_role; ?>
<div class="header-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-lg-4 text-left pull-left"><a href="/dashboard" class="logo">GlobalLogic Appraisal System</a></div>
            <div class="col-md-8 col-sm-8 col-lg-8 text-right pull-right top-link">

                <div class="menu-hover">
                    <a href="#" ><i class="fa fa-user"></i>
                        <?php //echo $this->layout()->users_info->name; ?></a>
                    <div class="sub" style="display: none;">
                        <ul class="sub-options">
                            <li><a style="font-size:14px;" href="/logout"><i class="fa fa-power-off"></i> Logout</a></li>
                        </ul>
                    </div>
                </div>
                <?php if (!empty($role_id) && $role_id == 1) { ?>
                    <a href="/user"><i class="fa fa-users"></i>
                        User Management</a>
                    <a href="/clientlist"><i class="fa fa-users"></i> Client List</a>
                    <a href="/folderlist"><i class="fa fa-users"></i> Folder Management</a>
                <?php } ?>
            </div>


        </div>
    </div>
</div>
<script>
    $(document).ready(function ()
    {
        $(".menu-hover").hover(
                function () {
                    $(".sub").slideToggle(400);
                },
                function () {
                    $(".sub").hide();
                }
        );
    });
</script>